### PR TITLE
Make BasicArchitectureModel a dataclass

### PR DESCRIPTION
**Pull request by dexter2206**
## Description

This simply makes `BasicArchitectureModel` a dataclass to address a problem reported by @1ethanhansen.

## Please verify that you have completed the following steps

- [x] I have self-reviewed my code.
- [x] I have included test cases validating introduced feature/fix.
- [x] I have updated documentation.

### CODE REVIEW

**Review by 1ethanhansen — APPROVED** [review]
LGTM!

**Comment by 1ethanhansen** [comment]
Looking at the error in the test suite, looks like `scipy.linalg.solve` is getting an unexpected arg `sym_pos` which exists [in scipy 1.10.1](https://docs.scipy.org/doc/scipy-1.10.1/reference/generated/scipy.linalg.solve.html) but not in the [latest stable 1.11.0](https://docs.scipy.org/doc/scipy-1.11.0/reference/generated/scipy.linalg.solve.html). Not sure how to fix, but thought the context might be helpful @dexter2206

**Comment by AthenaCaesura** [comment]
I have introduced [this PR](https://github.com/zapatacomputing/orquestra-quantum/pull/83) into `orquestra-quantum` which limits the version of scipy to 1.10.1. Once that is approved, we can continue here. 🙂

**Comment by 1ethanhansen** [comment]
Only one test is failing after a merge that caused no changes (according to git diff)... I'm going to try re-running

**Pull request merged**
